FROM rakjin/kong-nodejs

RUN apt-get install -y \
        libssl-dev \
        libreadline-dev \
        zlib1g-dev \
        ;

USER kong
    WORKDIR /home/kong
    RUN git clone https://github.com/sstephenson/rbenv.git .rbenv && \
        git clone https://github.com/sstephenson/ruby-build.git .rbenv/plugins/ruby-build && \
        echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc && \
        echo 'eval "$(rbenv init -)"' >> ~/.bashrc && \
        export PATH="$HOME/.rbenv/bin:$PATH" && \
        eval "$(rbenv init -)" && \
        rbenv install 2.1.5 && \
        rbenv global 2.1.5 && \
        gem install bundler
USER root

