#!/usr/bin/env bash
set -e

IMAGE="${1:-rakjin/kong}"

mkdir -p data
CID=$(docker run -dp 127.0.0.1::22 -v `pwd`/data:/home/kong/data "$IMAGE")
docker cp ~/.ssh/id_rsa     "$CID":/home/kong/.ssh/
docker cp ~/.ssh/id_rsa.pub "$CID":/home/kong/.ssh/
docker cp ~/.ssh/id_rsa.pub "$CID":/home/kong/.ssh/authorized_keys
docker exec "$CID" sh -c 'chown kong:kong /home/kong/.ssh/*'
SSH_PORT=$(docker port "$CID" 22 | cut -d ":" -f 2)
ssh -o LogLevel=quiet \
    -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no \
    -p "$SSH_PORT" kong@127.0.0.1
